name: Terraform Destroy

permissions:
  write-all

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          role-session-name: aws-auth
          aws-region: us-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Initialize Terraform
        run: terraform init

      - name: Delete Node Group First
        run: |
          aws eks delete-nodegroup --cluster-name eks-non-prod --nodegroup-name eks-non-prod-node-group --region us-east-1 || true
          aws eks wait nodegroup-deleted --cluster-name eks-non-prod --nodegroup-name eks-non-prod-node-group --region us-east-1 || true

      - name: Terraform Destroy
        run: terraform destroy -var-file="terraform.tfvars" -auto-approve
